---
driver:
  name: vagrant
  customize:
    memory: 2048
    numvcpus: 2
    vhv.enable: TRUE

provisioner:
  name: chef_zero
  require_chef_omnibus: 11.12.8

platforms:
  - name: fedora-20

suites:
  - name: default
    run_list: recipe[halvm]
    attributes:
