name             'halvm'
description      'Installs & Configures a HalVM Host'
version          '1.0.0'
maintainer       'Darrin Eden'
maintainer_email 'darrin@dje.io'
license          'Apache 2.0'
supports         'fedora', '= 20'
depends          'build-essential'
depends          'cabal'
depends          'git'
